import type { PlaceRecord } from "@/features/places/types";

export const mockPlaces: PlaceRecord[] = [
  {
    id: "school-gimbap",
    name: "학교앞김밥",
    businessName: "학교앞김밥 성신점",
    categorySlug: "bunsik",
    address: "서울 성북구 동소문로22길 31",
    district: "서울 성북구",
    latitude: 37.5924,
    longitude: 127.0171,
    representativePriceAmount: 3500,
    representativePriceLabel: "참치김밥",
    verificationStatus: "verified",
    lastPriceUpdatedAt: "2026-03-28",
    description:
      "학교와 지하철 사이 골목에 있는 분식집입니다. 혼밥 수요가 많고 빠르게 식사하기 좋습니다.",
    note: "점심시간에는 포장 줄이 짧은 편입니다.",
    likeCount: 18,
    dislikeCount: 1,
    viewerReaction: null,
    priceItems: [
      {
        id: "school-gimbap-1",
        label: "참치김밥",
        amount: 3500,
        verificationStatus: "verified",
        reportedAt: "2026-03-28",
      },
      {
        id: "school-gimbap-2",
        label: "라볶이",
        amount: 5000,
        verificationStatus: "verified",
        reportedAt: "2026-03-28",
      },
      {
        id: "school-gimbap-3",
        label: "잔치국수",
        amount: 4500,
        verificationStatus: "unverified",
        reportedAt: "2026-03-27",
      },
    ],
    history: [
      {
        id: "school-gimbap-h1",
        label: "참치김밥",
        amount: 3200,
        verificationStatus: "verified",
        recordedAt: "2026-01-10",
      },
      {
        id: "school-gimbap-h2",
        label: "참치김밥",
        amount: 3500,
        verificationStatus: "verified",
        recordedAt: "2026-03-28",
      },
    ],
    comments: [
      {
        id: "school-gimbap-c1",
        authorLabel: "근처 자취생",
        body: "가성비는 좋고 김밥 재료가 꾸준히 비슷합니다.",
        createdAt: "2026-03-28",
      },
    ],
  },
  {
    id: "budget-baekban",
    name: "든든백반",
    businessName: "든든백반 혜화점",
    categorySlug: "korean",
    address: "서울 종로구 대학로11길 18",
    district: "서울 종로구",
    latitude: 37.5832,
    longitude: 127.0029,
    representativePriceAmount: 7000,
    representativePriceLabel: "오늘의 백반",
    verificationStatus: "verified",
    lastPriceUpdatedAt: "2026-03-29",
    description:
      "백반, 찌개, 제육류를 파는 직장인 점심 식당입니다. 기본 반찬이 안정적입니다.",
    note: "13시 이후 방문 시 대기 없이 식사하기 쉽습니다.",
    likeCount: 12,
    dislikeCount: 0,
    viewerReaction: null,
    priceItems: [
      {
        id: "budget-baekban-1",
        label: "오늘의 백반",
        amount: 7000,
        verificationStatus: "verified",
        reportedAt: "2026-03-29",
      },
      {
        id: "budget-baekban-2",
        label: "김치찌개",
        amount: 7500,
        verificationStatus: "verified",
        reportedAt: "2026-03-29",
      },
      {
        id: "budget-baekban-3",
        label: "제육볶음",
        amount: 8500,
        verificationStatus: "unverified",
        reportedAt: "2026-03-25",
      },
    ],
    history: [
      {
        id: "budget-baekban-h1",
        label: "오늘의 백반",
        amount: 6500,
        verificationStatus: "verified",
        recordedAt: "2025-12-02",
      },
      {
        id: "budget-baekban-h2",
        label: "오늘의 백반",
        amount: 7000,
        verificationStatus: "verified",
        recordedAt: "2026-03-29",
      },
    ],
    comments: [
      {
        id: "budget-baekban-c1",
        authorLabel: "회사원",
        body: "계란후라이가 추가될 때 만족도가 높습니다.",
        createdAt: "2026-03-29",
      },
    ],
  },
  {
    id: "onsaemiro-laundry",
    name: "온새미로세탁",
    businessName: "온새미로세탁소",
    categorySlug: "laundry",
    address: "서울 동작구 상도로41길 7",
    district: "서울 동작구",
    latitude: 37.4994,
    longitude: 126.9516,
    representativePriceAmount: 2500,
    representativePriceLabel: "셔츠 1벌",
    verificationStatus: "verified",
    lastPriceUpdatedAt: "2026-03-24",
    description:
      "동네 단골이 많은 세탁소입니다. 셔츠와 바지 기본 세탁 가격이 비교적 안정적입니다.",
    note: "현금 결제 시 빠른 수령 안내를 해주는 편입니다.",
    likeCount: 9,
    dislikeCount: 1,
    viewerReaction: null,
    priceItems: [
      {
        id: "onsaemiro-laundry-1",
        label: "셔츠 1벌",
        amount: 2500,
        verificationStatus: "verified",
        reportedAt: "2026-03-24",
      },
      {
        id: "onsaemiro-laundry-2",
        label: "바지 1벌",
        amount: 3500,
        verificationStatus: "verified",
        reportedAt: "2026-03-24",
      },
    ],
    history: [
      {
        id: "onsaemiro-laundry-h1",
        label: "셔츠 1벌",
        amount: 2300,
        verificationStatus: "verified",
        recordedAt: "2025-11-15",
      },
      {
        id: "onsaemiro-laundry-h2",
        label: "셔츠 1벌",
        amount: 2500,
        verificationStatus: "verified",
        recordedAt: "2026-03-24",
      },
    ],
    comments: [
      {
        id: "onsaemiro-laundry-c1",
        authorLabel: "근처 주민",
        body: "맡긴 날짜보다 하루 빨리 나오는 경우가 있습니다.",
        createdAt: "2026-03-24",
      },
    ],
  },
  {
    id: "dongne-mart24",
    name: "동네마트24",
    businessName: "동네마트24",
    categorySlug: "mart",
    address: "서울 마포구 월드컵북로 84",
    district: "서울 마포구",
    latitude: 37.5636,
    longitude: 126.9087,
    representativePriceAmount: 2980,
    representativePriceLabel: "1+1 생수 묶음",
    verificationStatus: "unverified",
    lastPriceUpdatedAt: "2026-03-21",
    description:
      "대형마트는 아니지만 일상 장보기 가격이 괜찮은 동네형 마트입니다.",
    note: "행사 진열대 가격표 업데이트가 느릴 수 있습니다.",
    likeCount: 7,
    dislikeCount: 2,
    viewerReaction: null,
    priceItems: [
      {
        id: "dongne-mart24-1",
        label: "1+1 생수 묶음",
        amount: 2980,
        verificationStatus: "unverified",
        reportedAt: "2026-03-21",
      },
      {
        id: "dongne-mart24-2",
        label: "계란 10구",
        amount: 4200,
        verificationStatus: "unverified",
        reportedAt: "2026-03-20",
      },
    ],
    history: [
      {
        id: "dongne-mart24-h1",
        label: "계란 10구",
        amount: 3900,
        verificationStatus: "unverified",
        recordedAt: "2026-02-14",
      },
      {
        id: "dongne-mart24-h2",
        label: "계란 10구",
        amount: 4200,
        verificationStatus: "unverified",
        recordedAt: "2026-03-20",
      },
    ],
    comments: [
      {
        id: "dongne-mart24-c1",
        authorLabel: "장보기 사용자",
        body: "행사 상품은 좋지만 품절이 빠른 편입니다.",
        createdAt: "2026-03-21",
      },
    ],
  },
  {
    id: "print-station",
    name: "프린트스테이션",
    businessName: "프린트스테이션 신촌점",
    categorySlug: "print",
    address: "서울 서대문구 연세로5다길 12",
    district: "서울 서대문구",
    latitude: 37.5588,
    longitude: 126.9368,
    representativePriceAmount: 80,
    representativePriceLabel: "흑백 출력 1장",
    verificationStatus: "verified",
    lastPriceUpdatedAt: "2026-03-30",
    description:
      "학생과 취준생 수요가 많은 출력 전문점입니다. 기본 출력과 제본 가격이 명확한 편입니다.",
    note: "USB보다 메일 전송 출력이 빠릅니다.",
    likeCount: 15,
    dislikeCount: 1,
    viewerReaction: null,
    priceItems: [
      {
        id: "print-station-1",
        label: "흑백 출력 1장",
        amount: 80,
        verificationStatus: "verified",
        reportedAt: "2026-03-30",
      },
      {
        id: "print-station-2",
        label: "컬러 출력 1장",
        amount: 300,
        verificationStatus: "verified",
        reportedAt: "2026-03-30",
      },
      {
        id: "print-station-3",
        label: "스프링 제본",
        amount: 2500,
        verificationStatus: "unverified",
        reportedAt: "2026-03-18",
      },
    ],
    history: [
      {
        id: "print-station-h1",
        label: "흑백 출력 1장",
        amount: 70,
        verificationStatus: "verified",
        recordedAt: "2025-10-03",
      },
      {
        id: "print-station-h2",
        label: "흑백 출력 1장",
        amount: 80,
        verificationStatus: "verified",
        recordedAt: "2026-03-30",
      },
    ],
    comments: [
      {
        id: "print-station-c1",
        authorLabel: "대학생",
        body: "오전 시간대는 거의 대기 없이 바로 출력됩니다.",
        createdAt: "2026-03-30",
      },
    ],
  },
  {
    id: "kind-pharmacy",
    name: "착한약국",
    businessName: "착한약국",
    categorySlug: "pharmacy",
    address: "서울 관악구 남부순환로 1820",
    district: "서울 관악구",
    latitude: 37.4814,
    longitude: 126.9521,
    representativePriceAmount: 2500,
    representativePriceLabel: "기본 상비약",
    verificationStatus: "verified",
    lastPriceUpdatedAt: "2026-03-26",
    description:
      "일반 상비약 가격이 비교적 낮고 상담이 친절한 동네 약국입니다.",
    note: "저녁 시간 방문객이 많습니다.",
    likeCount: 8,
    dislikeCount: 3,
    viewerReaction: null,
    priceItems: [
      {
        id: "kind-pharmacy-1",
        label: "기본 상비약",
        amount: 2500,
        verificationStatus: "verified",
        reportedAt: "2026-03-26",
      },
      {
        id: "kind-pharmacy-2",
        label: "진통제 10정",
        amount: 3000,
        verificationStatus: "verified",
        reportedAt: "2026-03-26",
      },
    ],
    history: [
      {
        id: "kind-pharmacy-h1",
        label: "진통제 10정",
        amount: 2800,
        verificationStatus: "verified",
        recordedAt: "2025-12-19",
      },
      {
        id: "kind-pharmacy-h2",
        label: "진통제 10정",
        amount: 3000,
        verificationStatus: "verified",
        recordedAt: "2026-03-26",
      },
    ],
    comments: [
      {
        id: "kind-pharmacy-c1",
        authorLabel: "동네 주민",
        body: "처방전 없이 살 수 있는 기본 약 가격이 무난합니다.",
        createdAt: "2026-03-26",
      },
    ],
  },
];
